### ISSUE TITLE
求助：运行出错

### ISSUE THREAD

**Issue by guanyu2000** [OSUSecLab/TaintMini#1]
输入路径为小程序的app.json
输入：python main.py -i  路径
得到  UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 472: illegal multibyte sequence  的报错，求助

**Comment by chaowangsec** [comment]
可以提供更多信息吗，例如操作系统/报错调用栈等。通过已有的信息，可能是小程序文件路径存在中文字符？

Please provide more information like os, error stack, etc. I'm guessing there're Chinese characters in the app path?

**Comment by guanyu2000** [comment]
作者您好，我把小程序放在了没有中文路径的文件夹里，报错依旧为之前截图那样。请问您可以提供以下您那边的测试用例吗？




李冠宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OSUSecLab/TaintMini"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月9日(星期五) 凌晨0:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OSUSecLab/TaintMini] 求助：运行出错 (Issue #1)





 
可以提供更多信息吗，例如操作系统/报错调用栈等。通过已有的信息，可能是小程序文件路径存在中文字符？
 
Please provide more information like os, error stack, etc. I'm guessing there're Chinese characters in the app path?

**Comment by guanyu2000** [comment]
尊敬的taintmini作者您好，我的小程序路径不包含中文，报错仍如之前那样。您那边方便提供测试小程序用例嘛




李冠宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OSUSecLab/TaintMini"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月9日(星期五) 凌晨0:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OSUSecLab/TaintMini] 求助：运行出错 (Issue #1)





 
可以提供更多信息吗，例如操作系统/报错调用栈等。通过已有的信息，可能是小程序文件路径存在中文字符？
 
Please provide more information like os, error stack, etc. I'm guessing there're Chinese characters in the app path?

**Comment by chaowangsec** [comment]
李冠宇您好，像上一条评论所述，请您提供更多信息。我们无法从一行报错信息发现问题的源头。

> 报错依旧为之前截图那样

我们没有找到任何截图，请您检查相关评论细节

关于测试小程序用例，由于潜在法律与道德风险，我们无法提供小程序用于公开测试。

如果您想要小程序数据集用于科研等目的，依腾讯公司的要求，请您使用您的组织邮箱发送邮件至 wang.15147@osu.edu 或 zhang.12047@osu.edu 并抄送 zlin@cse.ohio-state.edu，并说明大致科研目的及用途。我们在审核后会通过私有链接分享部分数据集给您。

如果您想要单个或少量小程序用于测试，请您使用网络上其他方法下载。同样由于潜在法律风险，我们无法分享相关链接，请您在网络上自行搜索。

如有任何不便还请您谅解。

**Comment by guanyu2000** [comment]
尊敬的作者，感谢您在百忙之中的回复，目前我是一名大学学生，准备读研，导师推荐给我这篇论文，我想深入学习一下。这是我的目的和用途。
我在github找到了小程序的解包工具，并解包了“问卷星”小程序，运行taintmini小程序输入它的文件路径，结果总是“no page found”。
我想知道在输入时应输入小程序整个文件夹的地址还是app.json文件的文件地址呢？






李冠宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OSUSecLab/TaintMini"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月14日(星期三) 凌晨3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OSUSecLab/TaintMini] 求助：运行出错 (Issue #1)





 
李冠宇您好，像上一条评论所述，请您提供更多信息。我们无法从一行报错信息发现问题的源头。
  
报错依旧为之前截图那样
  
我们没有找到任何截图，请您检查相关评论细节
 
关于测试小程序用例，由于潜在法律与道德风险，我们无法提供小程序用于公开测试。
 
如果您想要小程序数据集用于科研等目的，依腾讯公司的要求，请您使用您的组织邮箱发送邮件至 ***@***.*** 或 ***@***.*** 并抄送 ***@***.***，并说明大致科研目的及用途。我们在审核后会通过私有链接分享部分数据集给您。
 
如果您想要单个或少量小程序用于测试，请您使用网络上其他方法下载。同样由于潜在法律风险，我们无法分享相关链接，请您在网络上自行搜索。
 
如有任何不便还请您谅解。

**Comment by chaowangsec** [comment]
尊敬的李冠宇您好，输入时请输入小程序根文件夹的路径。例如：如果 `app.json` 的路径为 `/path/to/miniapp/app.json`，请传递 `/path/to/miniapp` 给 `--input` 参数。

如果有更多问题欢迎继续评论，还烦请提供更多细节信息以供我们找到问题所在与解决方案，谢谢！

**Comment by guanyu2000** [comment]
尊敬的作者您好，小程序的报错依旧如下图，报错相同且重复很多次。我更改了中文路径，仍然显示以下错误。

报错中还夹杂着：

请问该怎么办呢




李冠宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OSUSecLab/TaintMini"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 凌晨1:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [OSUSecLab/TaintMini] 求助：运行出错 (Issue #1)





 
尊敬的李冠宇您好，输入时请输入小程序根文件夹的路径。例如：如果 app.json 的路径为 /path/to/miniapp/app.json，请传递 /path/to/miniapp 给 --input 参数。
 
如果有更多问题欢迎继续评论，还烦请提供更多细节信息以供我们找到问题所在与解决方案，谢谢！

**Comment by evi0s** [comment]
李冠宇您好，您的图片和报错信息均无法显示/查看，请您使用 GitHub 网页评论并添加附件。同时，我们更欢迎纯文本报错信息以供查看。

**Comment by chaowangsec** [comment]
李冠宇您好，您的图片和报错信息均无法显示/查看，请您使用 GitHub 网页评论并添加附件。同时，我们更欢迎纯文本报错信息以供查看。

**Comment by chaowangsec** [comment]
Since there's no follow up, I'm closing this issue. Please feel free to re-open it if you have more questions.
