### ISSUE TITLE
关于同一个小程序不同页面间的数据流的疑问

### ISSUE THREAD

**Issue by ppflower** [OSUSecLab/TaintMini#2]
尊敬的TaintMini作者，您好。

我近期正尝试用TaintMini做一些关于小程序的分析。论文中提到TaintMini有能力处理不同页面之间的数据流，即论文Figure2中标号为③的数据流向箭头。我使用用论文中提供的代码片段以及其他的样本测试发现输出没有包含预期结果。我阅读了相关代码，但是未找到处理小程序页面间数据流的代码（包括通过navigateTo函数的url参数传递数据，以及通过eventChannel传递数据）。请问这部分的具体实现在哪里呢？
测试用的关键代码如下，另外附件里包含了完整的代码文件。按我的预期，工具应当能够发现从`var d = wx.getStorageSync("phone");`到`console.log(obj);`的数据流，但实际输出结果中并未包含该数据流。
```
// config.json
{
  "sources": ["wx.getStorageSync"],
  "sinks": ["console.log", "wx.navigateTo"]
}
```
```
// index.js
Page({
    data: {
    },
    onLoad: function (options) {
        var d = wx.getStorageSync("phone");

        wx.navigateTo({
            url: "/pages/test1/test1",
            success: function(res) {
                res.eventChannel.emit('sinkPage', {data: 
                    {phone: d}
                });
            }
        });
    },
    globalData: {
        userInfo: null
    }
});
```
```
// test1.js
Page({
    data: {
    },
    onLoad: function (option) {
        var evChannel = this.getOpenerEventChannel();
        evChannel.on("sinkPage", function (data) {
            var obj = data.phone;
            console.log(obj);
        })
    }
})
```
[TestGWY.zip](https://github.com/OSUSecLab/TaintMini/files/11749469/TestGWY.zip)

**Comment by evi0s** [comment]
您好！很抱歉出现此类问题。该部分代码已经在本地修改但尚未提交到 GitHub。由于这部分代码还有改进空间，我已将本地代码提交至 [`unstable`](https://github.com/OSUSecLab/TaintMini/tree/unstable) 分支，请您在 pull 后 checkout 至 `unstable` 分支后再运行测试代码。

非常感谢您测试并提供详细的问题报告，欢迎您继续提交 issues。此外，如果方便的话，请您还使用英文提交，方便整个社区。

**Comment by chaowangsec** [comment]
您好！很抱歉出现该问题，该部分代码在本地修改后没有提交到 GitHub。由于该部分代码还有改进空间，且修改了部分函数返回结构，我已经将该代码提交至了 [`unstable`](https://github.com/OSUSecLab/TaintMini/tree/unstable) 分支。请您在 pull 后 checkout 至该分支运行相关测试。我们以后会持续更新并推送至该分支。

感谢您详细的报告！欢迎您以后提交更多报告以帮助提升我们的代码质量。此外，如果方便的话，还请您使用英文提交报告，方便整个社区查看并检索。谢谢！

**Comment by chaowangsec** [comment]
Since there's no follow up, I'm closing this issue. Please feel free to re-open it if you have more questions regarding this thread.
If you have different issues regarding our tool, please feel free to open another issue so that we can try to help. Thanks.
